import { html, GemElement, customElement } from '@mantou/gem';
import '@mantou/gem/elements/link';

@customElement('gem-book-footer')
export class Footer extends GemElement {
  render() {
    return html`
      <style>
        :host {
          display: block;
          grid-area: auto / content;
          padding: 2rem 0;
          margin-top: 6rem;
          border-top: 1px solid var(--border-color);
        }
        gem-link {
          color: var(--link-color);
          text-decoration: none;
        }
        gem-link:hover {
          text-decoration: underline;
        }
      </style>
      Generated by ${html`<gem-link href="https://github.com/mantou132/gem-book">${'<gem-book>'}</gem-link>`}.
    `;
  }
}
